Finished RankingResults View
atlant04/Guess-E pull request #26
Opened 2023-04-06 17:19 UTC by nac5504

#25

2023-04-06 17:23 UTC, atlant04 commented
damn, I can barely keep up with this pace, I'll let Aziz handle this one

2023-04-06 17:25 UTC, nac5504 commented
haha the 3 I did are all basically the same view.

2023-04-06 17:38 UTC, azooz2003-bit commented
> haha the 3 I did are all basically the same view.

Looks good. Just allow the image to fill the top view instead of fitting. OpenAI's images have width = height, so the images should cover the white space.

2023-04-06 17:40 UTC, azooz2003-bit commented
> > haha the 3 I did are all basically the same view.
> 
> Looks good. Just allow the image to fill the top view instead of fitting. OpenAI's images have width = height, so the images should cover the white space.

I think u have to increase the zstack's frame.

2023-04-06 17:41 UTC, azooz2003-bit requested changes
Looks good. Just allow the image to fill the top view instead of fitting. OpenAI's images have width = height, so the images should cover the white space.

2023-04-07 01:24 UTC, atlant04 commented on Guess-E/RankingResultsView.swift
> +                    }.frame(height: geo.size.height * 0.45)
is there a way to avoid this without using the `GeometryReader`. It's really picky and leads to a lot of layout weirdness. Plus, you are containing `GeometryReader` to be 394x394, you can just use those numbers instead of `geo.size.width` etc

2023-04-07 18:55 UTC, azooz2003-bit commented
I agree with max here, please use fixed values. Also, just noticed the timer doesn't reach the end of the bar when at 0.

2023-04-12 02:06 UTC, azooz2003-bit approved these changes
@nac5504 Approving this for now, but pls make the last change.

2023-04-12 02:06 UTC, merged